# -*- coding: utf-8 -*-
"""Proyecto corte 1 Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UgiWVLWcufAhzEANu3sQi2IjEe8JZ9Ze

#**Árbol de decisión**

En esta sección vamos a trabajar con el dataset Breast Cancer Wisconsin para entrenar y evaluar un modelo de Árbol de Decisión. El flujo completo es: cargar y explorar los datos, dividirlos en entrenamiento y prueba, construir un pipeline de preprocesamiento, entrenar primero un árbol sin restricciones para evidenciar sobreajuste, visualizarlo, y luego ajustar sus hiperparámetros con GridSearchCV para obtener un modelo más balanceado. Al final comparamos el desempeño del árbol antes y después del ajuste.

Antes de trabajar con los datos necesitamos traer las herramientas que vamos a usar en toda la sección. numpy y pandas sirven para manejar los datos en forma de tablas y arreglos numéricos, matplotlib para graficar. De sklearn importamos: la función para cargar el dataset (load_breast_cancer), las herramientas para dividir los datos y ajustar hiperparámetros (train_test_split, GridSearchCV), las piezas para construir el pipeline de preprocesamiento (Pipeline, ColumnTransformer, StandardScaler), el clasificador y su visualización (DecisionTreeClassifier, plot_tree), y las métricas para evaluar qué tan bien predice el modelo (accuracy_score, classification_report, confusion_matrix).
"""

# Librerias basicas para manejo de datos y graficas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Dataset que vamos a usar (ya viene incluido en sklearn)
from sklearn.datasets import load_breast_cancer

# Herramientas para dividir los datos y buscar los mejores hiperparametros
from sklearn.model_selection import train_test_split, GridSearchCV

# Piezas para armar el pipeline de preprocesamiento
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

# El modelo que vamos a entrenar (Arbol de Decision) y su visualizacion
from sklearn.tree import DecisionTreeClassifier, plot_tree

# Metricas para evaluar que tan bien predice el modelo
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

"""Antes de entrenar cualquier modelo necesitamos traer los datos y entender qué tenemos entre manos. Cargamos el dataset Breast Cancer Wisconsin directamente desde sklearn, lo convertimos a un DataFrame de pandas para poder verlo y manipularlo como una tabla, y separamos las variables predictoras (X) de la variable objetivo (y, que indica si el tumor es maligno o benigno). Después hacemos una exploración rápida: cuántas filas y columnas hay, cómo se ven las primeras filas, y cuántos casos hay de cada clase, para saber si el dataset está balanceado o no."""

# Cargamos el dataset directamente desde sklearn
data = load_breast_cancer()

# Convertimos a DataFrame para trabajar mas comodo
X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name='target')

# target = 0 significa maligno, target = 1 significa benigno
print("Forma de X (filas, columnas):", X.shape)
print("\nPrimeras filas de X:")
print(X.head())

# Vemos cuantos casos hay de cada clase (maligno vs benigno)
print("\nDistribucion de clases:")
print(y.value_counts())
print("\nNombres de las clases:", data.target_names)

"""Dividimos los datos en entrenamiento (80%) y prueba (20%), usando stratify=y para que ambos conjuntos mantengan la misma proporción de casos malignos y benignos. Luego verificamos los tamaños y las proporciones de clase en cada conjunto.

"""

# Dividimos en 80/20, manteniendo la proporcion de clases con stratify
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Revisamos cuantas filas quedaron en cada conjunto
print("Tamano de entrenamiento:", X_train.shape)
print("Tamano de prueba:", X_test.shape)

# Confirmamos que la proporcion de clases se mantuvo similar en ambos
print("\nProporcion de clases en entrenamiento:")
print(y_train.value_counts(normalize=True))
print("\nProporcion de clases en prueba:")
print(y_test.value_counts(normalize=True))

"""Armamos el pipeline de preprocesamiento que después se conectará con el modelo. Como este dataset es todo numérico y no tiene datos faltantes, solo necesitamos una rama de escalado dentro del ColumnTransformer. La dejamos igual la estructura que se usará más adelante con KNN, aunque para el árbol el escalado no sea obligatorio."""

# Guardamos la lista de columnas numericas (aqui son todas)
columnas_numericas = X.columns.tolist()

# Pipeline numerico: solo escalado, no hay valores faltantes que imputar
num_pipe = Pipeline([
    ('scaler', StandardScaler())
])

# ColumnTransformer aplica el pipeline numerico a las columnas indicadas
preprocesador = ColumnTransformer([
    ('num', num_pipe, columnas_numericas)
])

"""Entrenamos un primer árbol sin limitar su profundidad ni ningún otro hiperparámetro, a propósito, para ver qué tan fácil sobreajusta. Comparamos el accuracy en entrenamiento contra el de prueba: si el primero es mucho más alto, es señal de que el árbol memorizó los datos en vez de aprender un patrón general."""

# Unimos el preprocesamiento con un arbol sin restricciones de hiperparametros
arbol_sin_restricciones = Pipeline([
    ('preprocesamiento', preprocesador),
    ('clasificador', DecisionTreeClassifier(random_state=42))
])

# Entrenamos el modelo
arbol_sin_restricciones.fit(X_train, y_train)

# Medimos el accuracy en entrenamiento y en prueba
train_acc = arbol_sin_restricciones.score(X_train, y_train)
test_acc = arbol_sin_restricciones.score(X_test, y_test)

print("Accuracy en entrenamiento:", train_acc)
print("Accuracy en prueba:", test_acc)

"""Dibujamos el árbol entrenado para ver cómo toma sus decisiones. Como el árbol sin restricciones puede tener demasiados niveles para verse bien en una figura, limitamos la visualización a los primeros 3 niveles — esto es solo para que se pueda leer el gráfico, el modelo entrenado no cambia."""

# Definimos el tamano de la figura para que se vea grande y legible
plt.figure(figsize=(20, 10))

# Graficamos el arbol, mostrando solo los primeros 3 niveles
plot_tree(
    arbol_sin_restricciones.named_steps['clasificador'],
    max_depth=3,
    feature_names=data.feature_names,
    class_names=data.target_names,
    filled=True,
    fontsize=8
)
plt.title("Arbol de Decision sin restricciones (mostrando solo 3 niveles)")
plt.show()

"""Ahora buscamos la mejor combinación de hiperparámetros para el árbol, en vez de dejarlo sin restricciones. Definimos un rango de valores a probar para max_depth, min_samples_split, min_samples_leaf y criterion, y usamos GridSearchCV para que pruebe todas las combinaciones con validación cruzada de 5 pliegues y se quede con la que mejor accuracy promedio obtenga."""

# Pipeline base que va a usar GridSearchCV para probar distintos hiperparametros
arbol_pipeline = Pipeline([
    ('preprocesamiento', preprocesador),
    ('clasificador', DecisionTreeClassifier(random_state=42))
])

# Rango de valores a probar para cada hiperparametro
param_grid = {
    'clasificador__max_depth': [2, 3, 4, 5, 6, 8, 10, None],
    'clasificador__min_samples_split': [2, 5, 10],
    'clasificador__min_samples_leaf': [1, 2, 5],
    'clasificador__criterion': ['gini', 'entropy']
}

# GridSearchCV prueba todas las combinaciones usando 5 pliegues de validacion cruzada
grid_search = GridSearchCV(
    arbol_pipeline,
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

# Entrenamos la busqueda (esto puede tardar un poco por la cantidad de combinaciones)
grid_search.fit(X_train, y_train)

print("Mejores hiperparametros encontrados:")
print(grid_search.best_params_)
print("\nMejor accuracy promedio en validacion cruzada:", grid_search.best_score_)

"""Tomamos el mejor modelo que encontró GridSearchCV y lo evaluamos sobre el conjunto de prueba, que no usamos ni para entrenar ni para elegir hiperparámetros. Revisamos el accuracy, el reporte de clasificación (precisión, recall y f1-score por clase) y la matriz de confusión, para ver exactamente en qué casos se equivoca el modelo."""

# Extraemos el mejor modelo encontrado por GridSearchCV
mejor_arbol = grid_search.best_estimator_

# Hacemos predicciones sobre el conjunto de prueba
y_pred = mejor_arbol.predict(X_test)

print("Accuracy en prueba (arbol ajustado):", accuracy_score(y_test, y_pred))

# Reporte con precision, recall y f1-score por clase
print("\nReporte de clasificacion:")
print(classification_report(y_test, y_pred, target_names=data.target_names))

# Matriz de confusion: muestra aciertos y errores por clase
print("\nMatriz de confusion:")
print(confusion_matrix(y_test, y_pred))

"""**Comparar árbol sin ajustar vs árbol ajustado**


Cerramos la sección poniendo lado a lado los resultados del árbol sin restricciones y el árbol ajustado, para ver claramente el efecto del ajuste de hiperparámetros sobre el sobreajuste. Estos números son los que necesitas para la tabla resumen del informe.
"""

print("Arbol SIN restricciones:")
print("  Accuracy entrenamiento:", train_acc)
print("  Accuracy prueba:", test_acc)

print("\nArbol AJUSTADO (con GridSearchCV):")
print("  Accuracy entrenamiento:", mejor_arbol.score(X_train, y_train))
print("  Accuracy prueba:", accuracy_score(y_test, y_pred))

print("\nGuarda estos numeros, los vas a necesitar para la tabla")
print("resumen del informe (entregable del proyecto).")

"""# **KNN**

En esta sección vamos a entrenar y evaluar un modelo KNN (K-Nearest Neighbors) sobre los mismos datos y la misma partición de entrenamiento/prueba que usamos con el árbol, para que la comparación entre ambos modelos sea justa. A diferencia del árbol, en KNN el escalado de las variables es obligatorio, así que construimos un pipeline de preprocesamiento propio para este modelo. Luego usamos el método del codo para tener una primera idea de qué valor de k funciona bien, ajustamos los hiperparámetros con GridSearchCV (número de vecinos, métrica de distancia y tipo de ponderación), y finalmente comparamos el desempeño de un KNN por defecto contra el KNN ya ajustado.
"""

# Lo unico nuevo que necesitamos para esta seccion: el clasificador KNN
from sklearn.neighbors import KNeighborsClassifier

"""Aunque X_train, X_test, y_train y y_test ya existen desde la sección del árbol, dejamos esta celda como constancia explícita en el código de que el KNN se está evaluando sobre exactamente los mismos datos y la misma partición (mismo random_state, mismo test_size, mismo stratify). Así, cualquiera que revise el notebook puede confirmar de un vistazo que la comparación entre árbol y KNN es justa, sin tener que rastrear hacia arriba en el notebook."""

# Dejamos esto como constancia: confirma que KNN usa el mismo dataset
# y la misma particion que el arbol (no es necesario ejecutarla si ya
# se corrieron las celdas del arbol antes, en el mismo notebook)
data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name='target')

# Mismos parametros de split que en la seccion del arbol
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Tamano de entrenamiento:", X_train.shape)
print("Tamano de prueba:", X_test.shape)

"""Construimos el pipeline de preprocesamiento para KNN. Aquí el escalado es obligatorio, no opcional: KNN mide distancias entre puntos, y una variable con escala más grande dominaría esa distancia sin ser necesariamente la más importante."""

# Guardamos la lista de columnas numericas (aqui son todas)
columnas_numericas = X.columns.tolist()

# Pipeline numerico para KNN: el escalado aqui es obligatorio, no opcional
num_pipe_knn = Pipeline([
    ('scaler', StandardScaler())
])

# ColumnTransformer aplica el escalado a las columnas indicadas
preprocesador_knn = ColumnTransformer([
    ('num', num_pipe_knn, columnas_numericas)
])

"""Probamos valores de k del 1 al 30 y graficamos el error de cada uno. Buscamos el punto donde el error deja de bajar (el "codo"), como primera pista de un buen valor de k."""

# Rango de valores de k a probar
valores_k = range(1, 31)
errores = []

# Entrenamos un KNN por cada valor de k y guardamos su error en prueba
for k in valores_k:
    knn_temp = Pipeline([
        ('preprocesamiento', preprocesador_knn),
        ('clasificador', KNeighborsClassifier(n_neighbors=k))
    ])
    knn_temp.fit(X_train, y_train)
    pred_temp = knn_temp.predict(X_test)
    error = 1 - accuracy_score(y_test, pred_temp)
    errores.append(error)

# Graficamos el error en funcion de k
plt.figure(figsize=(10, 6))
plt.plot(valores_k, errores, marker='o')
plt.xlabel('Numero de vecinos (k)')
plt.ylabel('Error de clasificacion (1 - accuracy)')
plt.title('Metodo del codo para elegir k')
plt.grid(True)
plt.show()

"""Buscamos la mejor combinación de k, métrica de distancia y ponderación con GridSearchCV. Prueba todas las combinaciones con validación cruzada de 5 pliegues y se queda con la mejor."""

# Pipeline base que GridSearchCV va a usar para probar combinaciones
knn_pipeline = Pipeline([
    ('preprocesamiento', preprocesador_knn),
    ('clasificador', KNeighborsClassifier())
])

# Rango de valores a probar: k, metrica de distancia y tipo de ponderacion
param_grid_knn = {
    'clasificador__n_neighbors': list(range(1, 31)),
    'clasificador__metric': ['euclidean', 'manhattan'],
    'clasificador__weights': ['uniform', 'distance']
}

# GridSearchCV prueba todas las combinaciones con 5 pliegues de validacion cruzada
grid_search_knn = GridSearchCV(
    knn_pipeline,
    param_grid_knn,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

# Entrenamos la busqueda (puede tardar por la cantidad de combinaciones)
grid_search_knn.fit(X_train, y_train)

print("Mejores hiperparametros encontrados:")
print(grid_search_knn.best_params_)
print("\nMejor accuracy promedio en validacion cruzada:", grid_search_knn.best_score_)

"""Tomamos el mejor modelo encontrado por GridSearchCV y lo evaluamos sobre el conjunto de prueba. Revisamos accuracy, reporte de clasificación y matriz de confusión."""

# Extraemos el mejor modelo encontrado por GridSearchCV
mejor_knn = grid_search_knn.best_estimator_

# Hacemos predicciones sobre el conjunto de prueba
y_pred_knn = mejor_knn.predict(X_test)

print("Accuracy en prueba (KNN ajustado):", accuracy_score(y_test, y_pred_knn))

# Reporte con precision, recall y f1-score por clase
print("\nReporte de clasificacion:")
print(classification_report(y_test, y_pred_knn, target_names=data.target_names))

# Matriz de confusion: muestra aciertos y errores por clase
print("\nMatriz de confusion:")
print(confusion_matrix(y_test, y_pred_knn))

"""Entrenamos un KNN con los valores por defecto (k=5) y lo comparamos contra el KNN ajustado. Estos números también van en la tabla resumen del informe."""

# KNN sin ajustar, usando el valor por defecto de k=5
knn_default = Pipeline([
    ('preprocesamiento', preprocesador_knn),
    ('clasificador', KNeighborsClassifier())  # k=5 por defecto
])
knn_default.fit(X_train, y_train)

print("KNN por defecto (k=5):")
print("  Accuracy entrenamiento:", knn_default.score(X_train, y_train))
print("  Accuracy prueba:", knn_default.score(X_test, y_test))

# Comparamos contra el KNN ya ajustado con GridSearchCV
print("\nKNN AJUSTADO (con GridSearchCV):")
print("  Accuracy entrenamiento:", mejor_knn.score(X_train, y_train))
print("  Accuracy prueba:", accuracy_score(y_test, y_pred_knn))

print("\nGuarda estos numeros junto con los del arbol para la tabla")
print("resumen del informe (entregable del proyecto).")

"""# **Sesgo-varianza**

En esta sección analizamos si el árbol y el KNN sufren de sobreajuste (alta varianza) o subajuste (alto sesgo), usando curvas de aprendizaje y curvas de validación para cada modelo.

Solo agregamos learning_curve y validation_curve, que son las únicas herramientas nuevas para esta sección; el resto ya está importado desde las secciones anteriores.
"""

# Lo unico nuevo que necesitamos para esta seccion
from sklearn.model_selection import learning_curve, validation_curve

"""Igual que en la sección de KNN, esto es redundante si ya corriste las celdas anteriores en el mismo notebook. La dejamos como constancia explícita de qué datos y qué split se usan en esta sección."""

# Dejamos esto como constancia: mismo dataset y misma particion
# que las secciones anteriores (no es necesario si ya se corrieron)
data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name='target')

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Lista de columnas numericas, usada mas adelante en el preprocesador
columnas_numericas = X.columns.tolist()

"""Reconstruimos los pipelines del árbol y de KNN, esta vez usando los mejores hiperparámetros encontrados con GridSearchCV, para que las curvas de aprendizaje y validación reflejen el modelo final, no uno con valores por defecto."""

# preprocesador ya existe desde la seccion del arbol; lo dejamos aqui
# como constancia de que ambos pipelines usan el mismo escalado
preprocesador = ColumnTransformer([
    ('num', Pipeline([('scaler', StandardScaler())]), columnas_numericas)
])

# Arbol con los mejores hiperparametros (los que dio GridSearchCV en su seccion)
arbol_pipeline = Pipeline([
    ('preprocesamiento', preprocesador),
    ('clasificador', DecisionTreeClassifier(
        max_depth=4,
        min_samples_split=2,
        min_samples_leaf=1,
        criterion='gini',
        random_state=42
    ))
])

# KNN con el mejor k encontrado (k=8), no el valor por defecto
knn_pipeline = Pipeline([
    ('preprocesamiento', preprocesador),
    ('clasificador', KNeighborsClassifier(n_neighbors=8, metric='euclidean', weights='distance'))
])

"""Creamos una función reutilizable para graficar la curva de aprendizaje de un modelo. Así evitamos repetir el mismo código para el árbol y para KNN."""

def graficar_curva_aprendizaje(pipeline, X, y, titulo):
    # learning_curve entrena el modelo con distintos tamanos de muestra
    # y devuelve el accuracy en entrenamiento y en validacion para cada uno
    tamanos_train, scores_train, scores_test = learning_curve(
        pipeline, X, y,
        cv=5,
        scoring='accuracy',
        train_sizes=np.linspace(0.1, 1.0, 10),
        random_state=42
    )

    # Promediamos los resultados de los 5 pliegues de validacion cruzada
    media_train = scores_train.mean(axis=1)
    media_test = scores_test.mean(axis=1)

    # Graficamos ambas curvas para comparar entrenamiento vs validacion
    plt.figure(figsize=(8, 5))
    plt.plot(tamanos_train, media_train, marker='o', label='Accuracy entrenamiento')
    plt.plot(tamanos_train, media_test, marker='o', label='Accuracy validacion')
    plt.xlabel('Numero de muestras de entrenamiento')
    plt.ylabel('Accuracy')
    plt.title(titulo)
    plt.legend()
    plt.grid(True)
    plt.show()

"""Usamos la función anterior para graficar la curva de aprendizaje del árbol con sus mejores hiperparámetros."""

graficar_curva_aprendizaje(
    arbol_pipeline, X_train, y_train,
    'Curva de aprendizaje - Arbol de Decision'
)

"""Variamos max_depth del 1 al 20 y vemos cómo cambia el accuracy de entrenamiento y validación en cada valor. Esto muestra en qué punto el árbol empieza a sobreajustar."""

rango_profundidad = range(1, 21)

# validation_curve entrena el modelo con cada valor de max_depth
# y devuelve el accuracy de entrenamiento y validacion en cada uno
scores_train_arbol, scores_test_arbol = validation_curve(
    arbol_pipeline, X_train, y_train,
    param_name='clasificador__max_depth',
    param_range=rango_profundidad,
    cv=5,
    scoring='accuracy'
)

# Graficamos ambas curvas para ver donde empieza el sobreajuste
plt.figure(figsize=(8, 5))
plt.plot(rango_profundidad, scores_train_arbol.mean(axis=1), marker='o', label='Accuracy entrenamiento')
plt.plot(rango_profundidad, scores_test_arbol.mean(axis=1), marker='o', label='Accuracy validacion')
plt.xlabel('max_depth')
plt.ylabel('Accuracy')
plt.title('Curva de validacion - Arbol de Decision (variando max_depth)')
plt.legend()
plt.grid(True)
plt.show()

"""Lo mismo, pero variando k del 1 al 30, para ver dónde aparece sobreajuste (k bajo) o subajuste (k alto)."""

rango_k = range(1, 31)

# Mismo principio que con el arbol, pero variando el numero de vecinos
scores_train_knn, scores_test_knn = validation_curve(
    knn_pipeline, X_train, y_train,
    param_name='clasificador__n_neighbors',
    param_range=rango_k,
    cv=5,
    scoring='accuracy'
)

plt.figure(figsize=(8, 5))
plt.plot(list(rango_k), scores_train_knn.mean(axis=1), marker='o', label='Accuracy entrenamiento')
plt.plot(list(rango_k), scores_test_knn.mean(axis=1), marker='o', label='Accuracy validacion')
plt.xlabel('k (numero de vecinos)')
plt.ylabel('Accuracy')
plt.title('Curva de validacion - KNN (variando k)')
plt.legend()
plt.grid(True)
plt.show()

"""# **Importancia de variables**

En esta sección identificamos qué variables aportan más a las decisiones del árbol, usando feature_importances_. Este análisis solo aplica al árbol, porque KNN no tiene un atributo equivalente.

Todo lo que necesita esta sección (pandas, matplotlib, DecisionTreeClassifier, etc.) ya se importó en secciones anteriores del mismo notebook, así que esta celda no agrega nada nuevo. La dejamos como referencia de qué usa esta sección.

Igual que en las secciones anteriores, esto es redundante si ya corriste las celdas de arriba. La dejamos como constancia explícita de qué datos y qué split se usan aquí.
"""

# Dejamos esto como constancia: mismo dataset y misma particion
# que las secciones anteriores (no es necesario si ya se corrieron)
data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name='target')

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

columnas_numericas = X.columns.tolist()

"""Reconstruimos el árbol ya ajustado (con los mismos hiperparámetros que encontró GridSearchCV), para calcular la importancia de variables directamente sobre el modelo final."""

# preprocesador ya existe desde secciones anteriores; lo dejamos
# aqui como constancia
preprocesador = ColumnTransformer([
    ('num', Pipeline([('scaler', StandardScaler())]), columnas_numericas)
])

# Arbol final, con los mejores hiperparametros encontrados por GridSearchCV
arbol_final = Pipeline([
    ('preprocesamiento', preprocesador),
    ('clasificador', DecisionTreeClassifier(
        max_depth=4,
        min_samples_split=2,
        min_samples_leaf=1,
        criterion='gini',
        random_state=42
    ))
])

arbol_final.fit(X_train, y_train)

"""Sacamos feature_importances_ del árbol entrenado. Este valor ya viene calculado con base en ganancia (reducción de impureza), no hace falta ningún cálculo adicional."""

# feature_importances_ mide cuanto reduce la impureza cada variable
# en todos los splits del arbol; no requiere calculo adicional
importancias = arbol_final.named_steps['clasificador'].feature_importances_

# Ordenamos de mayor a menor importancia
tabla_importancias = pd.DataFrame({
    'variable': data.feature_names,
    'importancia': importancias
}).sort_values('importancia', ascending=False)

print("Importancia de cada variable (ordenadas de mayor a menor):")
print(tabla_importancias)

"""Graficamos las 10 variables más importantes en un gráfico de barras horizontales, para verlas de forma clara."""

# Solo las 10 mas importantes, para que la grafica sea legible
top_10 = tabla_importancias.head(10)

plt.figure(figsize=(10, 6))
plt.barh(top_10['variable'], top_10['importancia'])
plt.xlabel('Importancia (reduccion de impureza)')
plt.title('Top 10 variables mas importantes - Arbol de Decision')
plt.gca().invert_yaxis()  # para que la mas importante quede arriba
plt.tight_layout()
plt.show()

"""Revisamos cuántas variables el árbol no usó en ningún split (importancia cero). Esto no significa que sean inútiles en general, solo que este árbol en particular no las necesitó."""

# Variables con importancia cero: el arbol no las uso en ningun split
sin_uso = tabla_importancias[tabla_importancias['importancia'] == 0]

print(f"Numero de variables que el arbol no uso en ningun split: {len(sin_uso)}")
print("\nEstas variables no aportaron a reducir la impureza en este arbol")
print("(no significa que sean inutiles en general, solo que este arbol")
print("en particular no las necesito con los hiperparametros elegidos).")